language: php

php:
  - 7.2
  - 7.3

before_script:
  - git clone https://github.com/pmmp/pthreads.git
  - cd pthreads
  - git checkout 6ca019c58b4fa09ee2ff490f2444e34bef0773d0
  - phpize
  - ./configure
  - make
  - make install
  - cd ..
  - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script:
  - php vendor/phpunit/phpunit/phpunit # use the phpunit specified in the composer.json so local and ci use the same version

notifications:
  email: false